version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"

    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "pytest*"
          - "ruff"
          - "mypy"
      development-dependencies:
        patterns:
          - "bandit"
          - "diff-cover"
          - "django-coverage-plugin"
          - "django-stubs"
          - "mypy"
          - "pre-commit"
          - "pytest*"
          - "ruff"
          - "types-markdown"

    ignore:
      - dependency-name: "django"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "daily"
